name: CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: with Node 13.x
      uses: actions/setup-node@v1
      with:
        node-version: '13.11'
    - run: |
        yarn
        yarn test
